create table cliente (id int8 generated by default as identity, email varchar(60), nome varchar(70), fone varchar(18), primary key (id));
create table entrega (id int8 generated by default as identity, data_finalizacao timestamp, data_pedido timestamp, destinatario_bairro varchar(255), destinatario_complemento varchar(255), destinatario_logradouro varchar(255), destinatario_nome varchar(255), destinatario_numero varchar(255), status varchar(255), taxa numeric(19, 2), cliente_id int8, primary key (id));
create table ocorrencia (id int8 generated by default as identity, data_registro timestamp, descricao varchar(255), entrega_id int8, primary key (id));
alter table if exists entrega add constraint FK6s5qo326hpov2shx1c5wmnofk foreign key (cliente_id) references cliente;
alter table if exists ocorrencia add constraint FKj41wa4v81bo2xkg4xgc3knae foreign key (entrega_id) references entrega;
